---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
options(tibble.print_min = 5)
```

# Conclusion {#conclusion}

In this project, spot rates from the Federal Reserve were analyzed along with their corresponding 
zero prices and returns over time. In addition, multiple hedging models
were implemented and analyzed. The simple regression hedging model outperformed the
two duration models, and was on par with the much more complicated multiplicative
regression model. This leads me to conclude that the simple regression model
is the most useful out of the four.

I was particularly impressed with how well the yield curve factors explained the variation
in the rates for other maturities. Using linear combinations of certain
maturity spot rates seems to create powerful explanatory variables for other maturities.

Further research could be done by including transactions costs in hedging performance
calculations. This would likely penalize the multiplicative regression even further.
Additionally, one could include thresholds that had to be hit before a certain
recommended change in the weights was actually made. This could combat the transaction
costs and would benefit the simple regression method along with the duration methods.
